### PR TITLE
avatars modal

### PR DESCRIPTION
**Pull request by dygy**

### CODE REVIEW

**Comment by dygy** [comment]
i also added nodemon to dependencies, becuase concurrently runs positively while you have no global nodemon, so it's even hard to understand why api does not work

**Comment by dygy** [comment]
https://github.com/delbaoliveira/react-spa/assets/23248488/1769c634-bf52-48bf-b207-abc0d8fccb69

**Comment by dygy** [comment]
https://github.com/delbaoliveira/react-spa/assets/23248488/b13da664-61f0-4771-a83d-a0da8b0551d3

**Review by delbaoliveira — APPROVED** [review]
Brilliant, thank you @dygy 🙏🏼

**Comment by dygy** [comment]
🖤

**Pull request merged**
